spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/summer
    driverClassName: com.mysql.jdbc.Driver
    username: summer
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug

